from schema.scheduling_schema import SchedulingSchema
from schema.scheduling_schema import SearchSchedulingByPatientNameSchema
from schema.doctor_schema import DoctorSchema, DoctorViewSchema, ListDoctorsSchema
from schema.aesthetic_procedures_schema import AestheticProceduresSchema, ListAestheticProcedureSchema, AestheticProcedureViewSchema
from schema.scheduling_schema import SchedulingSchema, SchedulingViewSchema, ListSchedulingSchema
from schema.error_schema import ErrorSchema

from schema.doctor_schema import view_doctor, view_doctors
from schema.aesthetic_procedures_schema import view_aesthetic_procedure, view_aesthetic_procedures
from schema.scheduling_schema import view_scheduling, view_schedulings